{{- /*
Copyright (c) 2004-present Facebook All rights reserved.
Use of this source code is governed by a BSD-style
license that can be found in the LICENSE file.
*/ -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "symphony.front.fullname" . }}
  labels: {{- include "symphony.front.metaLabels" . | nindent 4 }}
type: Opaque
stringData:
  MYSQL_PASS: {{ .Values.front.spec.mysql.pass | quote }}
  SESSION_TOKEN: {{ .Values.front.spec.session_token | quote }}
