{{- /*
Copyright (c) 2004-present Facebook All rights reserved.
Use of this source code is governed by a BSD-style
license that can be found in the LICENSE file.
*/ -}}
{{- if and .Values.serviceMonitor.enabled .Values.serviceMonitor.alerting.rules (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ template "symphony.fullname" . }}
  labels: {{- include "symphony.metaLabels" . | nindent 4 }}
  {{- with .Values.serviceMonitor.alerting.additionalLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  groups: {{- toYaml .Values.serviceMonitor.alerting.rules | nindent 4 }}
{{- end }}
