{{- /*
Copyright (c) 2004-present Facebook All rights reserved.
Use of this source code is governed by a BSD-style
license that can be found in the LICENSE file.
*/ -}}
{{- if .Values.store.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "symphony.store.serviceAccountName" . }}
  labels: {{- include "symphony.store.metaLabels" . | nindent 4 }}
  {{- with .Values.store.serviceAccount.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
{{- include "symphony.imagePullSecrets" . }}
{{- end }}
